// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Example.SampleResponseJsonTypes;

namespace Example.SampleResponseJsonTypes
{

    internal class Output1Item
    {

        [JsonProperty("PLU")]
        public string PLU { get; set; }

        [JsonProperty("Locationid")]
        public string Locationid { get; set; }

        [JsonProperty("Year")]
        public string Year { get; set; }

        [JsonProperty("Month")]
        public string Month { get; set; }

        [JsonProperty("Day")]
        public string Day { get; set; }

        [JsonProperty("YearDay")]
        public string YearDay { get; set; }

        [JsonProperty("WeekDay")]
        public string WeekDay { get; set; }

        [JsonProperty("Quantity")]
        public string Quantity { get; set; }

        [JsonProperty("Day-1")]
        public string Day1 { get; set; }

        [JsonProperty("Day-2")]
        public string Day2 { get; set; }

        [JsonProperty("Day-3")]
        public string Day3 { get; set; }

        [JsonProperty("Day-4")]
        public string Day4 { get; set; }

        [JsonProperty("Day-5")]
        public string Day5 { get; set; }

        [JsonProperty("Day-6")]
        public string Day6 { get; set; }

        [JsonProperty("Day-7")]
        public string Day7 { get; set; }

        [JsonProperty("Scored Labels")]
        public string ScoredLabels { get; set; }
    }

}
