// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Example.SampleResponseJsonTypes;

namespace Example
{

    internal class SampleResponse
    {

        [JsonProperty("Results")]
        public Results Results { get; set; }
    }

}
