// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Example.SampleResponseJsonTypes;

namespace Example.SampleResponseJsonTypes
{

    internal class Items
    {

        [JsonProperty("output1Item")]
        public Output1Item Output1Item { get; set; }
    }

}
